server:
  port: 9004
spring:
  thymeleaf:
    cache: false
  application:
    name: UserWeb004
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8888/eureka/,http://eureka2:9999/eureka/
USERPROVIDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule  #轮询
    ConnectTimeout: 250
    ReadTimeout: 250
    OkToRetryOnAllOperations: true
    # 切换实例的重试次数
    MaxAutoRetriesNextServer: 1
    # 对当前实例的重试次数
    MaxAutoRetries: 1
logging:
  level:
    com:
      openlab:
        debug
#启用fegin的熔断器
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
